### PR TITLE
Update metatests to v0.6.3

### PR DESCRIPTION
**Pull request by JuliaGerasymenko**

### CODE REVIEW

**Comment by tshemsedinov** [comment]
Land after https://github.com/metarhia/do/pull/38

**Comment by SemenchenkoVitaliy** [comment]
[metatests@0.6.2](https://www.npmjs.com/package/metatests) are available.

**Comment by tshemsedinov** [comment]
Yes, published today, @SemenchenkoVitaliy @JuliaGerasymenko

**Comment by tshemsedinov** [comment]
Landed in 0ce25b4

**Pull request closed without merging**
